In [2]:
import tensorflow as tf
def tables(x):
  for i in range(1,11):
    print(i,"X",x,"=",i*x)
for i in range(1,101):
  print("\n**********************",i,"th table******************************\n")
  tables(i)

********************** 1 th table******************************

1 X 1 = 1
2 X 1 = 2
3 X 1 = 3
4 X 1 = 4
5 X 1 = 5
6 X 1 = 6
7 X 1 = 7
8 X 1 = 8
9 X 1 = 9
10 X 1 = 10

********************** 2 th table******************************

1 X 2 = 2
2 X 2 = 4
3 X 2 = 6
4 X 2 = 8
5 X 2 = 10
6 X 2 = 12
7 X 2 = 14
8 X 2 = 16
9 X 2 = 18
10 X 2 = 20

********************** 3 th table******************************

1 X 3 = 3
2 X 3 = 6
3 X 3 = 9
4 X 3 = 12
5 X 3 = 15
6 X 3 = 18
7 X 3 = 21
8 X 3 = 24
9 X 3 = 27
10 X 3 = 30

********************** 4 th table******************************

1 X 4 = 4
2 X 4 = 8
3 X 4 = 12
4 X 4 = 16
5 X 4 = 20
6 X 4 = 24
7 X 4 = 28
8 X 4 = 32
9 X 4 = 36
10 X 4 = 40

********************** 5 th table******************************

1 X 5 = 5
2 X 5 = 10
3 X 5 = 15
4 X 5 = 20
5 X 5 = 25
6 X 5 = 30
7 X 5 = 35
8 X 5 = 40
9 X 5 = 45
10 X 5 = 50

********************** 6 th table******************************

1 X 6 = 6
2 X 6 = 12
3 X 6 = 18
4 X 6 = 24
5 X 6 = 30
6 X 6 = 36
7 X 6 = 42
8 X 6 = 48
9 X 6 = 54
10 X 6 = 60

********************** 7 th table******************************

1 X 7 = 7
2 X 7 = 14
3 X 7 = 21
4 X 7 = 28
5 X 7 = 35
6 X 7 = 42
7 X 7 = 49
8 X 7 = 56
9 X 7 = 63
10 X 7 = 70

********************** 8 th table******************************

1 X 8 = 8
2 X 8 = 16
3 X 8 = 24
4 X 8 = 32
5 X 8 = 40
6 X 8 = 48
7 X 8 = 56
8 X 8 = 64
9 X 8 = 72
10 X 8 = 80

********************** 9 th table******************************

1 X 9 = 9
2 X 9 = 18
3 X 9 = 27
4 X 9 = 36
5 X 9 = 45
6 X 9 = 54
7 X 9 = 63
8 X 9 = 72
9 X 9 = 81
10 X 9 = 90

********************** 10 th table******************************

1 X 10 = 10
2 X 10 = 20
3 X 10 = 30
4 X 10 = 40
5 X 10 = 50
6 X 10 = 60
7 X 10 = 70
8 X 10 = 80
9 X 10 = 90
10 X 10 = 100

********************** 11 th table******************************

1 X 11 = 11
2 X 11 = 22
3 X 11 = 33
4 X 11 = 44
5 X 11 = 55
6 X 11 = 66
7 X 11 = 77
8 X 11 = 88
9 X 11 = 99
10 X 11 = 110

********************** 12 th table******************************

1 X 12 = 12
2 X 12 = 24
3 X 12 = 36
4 X 12 = 48
5 X 12 = 60
6 X 12 = 72
7 X 12 = 84
8 X 12 = 96
9 X 12 = 108
10 X 12 = 120

********************** 13 th table******************************

1 X 13 = 13
2 X 13 = 26
3 X 13 = 39
4 X 13 = 52
5 X 13 = 65
6 X 13 = 78
7 X 13 = 91
8 X 13 = 104
9 X 13 = 117
10 X 13 = 130

********************** 14 th table******************************

1 X 14 = 14
2 X 14 = 28
3 X 14 = 42
4 X 14 = 56
5 X 14 = 70
6 X 14 = 84
7 X 14 = 98
8 X 14 = 112
9 X 14 = 126
10 X 14 = 140

********************** 15 th table******************************

1 X 15 = 15
2 X 15 = 30
3 X 15 = 45
4 X 15 = 60
5 X 15 = 75
6 X 15 = 90
7 X 15 = 105
8 X 15 = 120
9 X 15 = 135
10 X 15 = 150

********************** 16 th table******************************

1 X 16 = 16
2 X 16 = 32
3 X 16 = 48
4 X 16 = 64
5 X 16 = 80
6 X 16 = 96
7 X 16 = 112
8 X 16 = 128
9 X 16 = 144
10 X 16 = 160

********************** 17 th table******************************

1 X 17 = 17
2 X 17 = 34
3 X 17 = 51
4 X 17 = 68
5 X 17 = 85
6 X 17 = 102
7 X 17 = 119
8 X 17 = 136
9 X 17 = 153
10 X 17 = 170

********************** 18 th table******************************

1 X 18 = 18
2 X 18 = 36
3 X 18 = 54
4 X 18 = 72
5 X 18 = 90
6 X 18 = 108
7 X 18 = 126
8 X 18 = 144
9 X 18 = 162
10 X 18 = 180

********************** 19 th table******************************

1 X 19 = 19
2 X 19 = 38
3 X 19 = 57
4 X 19 = 76
5 X 19 = 95
6 X 19 = 114
7 X 19 = 133
8 X 19 = 152
9 X 19 = 171
10 X 19 = 190

********************** 20 th table******************************

1 X 20 = 20
2 X 20 = 40
3 X 20 = 60
4 X 20 = 80
5 X 20 = 100
6 X 20 = 120
7 X 20 = 140
8 X 20 = 160
9 X 20 = 180
10 X 20 = 200

********************** 21 th table******************************

1 X 21 = 21
2 X 21 = 42
3 X 21 = 63
4 X 21 = 84
5 X 21 = 105
6 X 21 = 126
7 X 21 = 147
8 X 21 = 168
9 X 21 = 189
10 X 21 = 210

********************** 22 th table******************************

1 X 22 = 22
2 X 22 = 44
3 X 22 = 66
4 X 22 = 88
5 X 22 = 110
6 X 22 = 132
7 X 22 = 154
8 X 22 = 176
9 X 22 = 198
10 X 22 = 220

********************** 23 th table******************************

1 X 23 = 23
2 X 23 = 46
3 X 23 = 69
4 X 23 = 92
5 X 23 = 115
6 X 23 = 138
7 X 23 = 161
8 X 23 = 184
9 X 23 = 207
10 X 23 = 230

********************** 24 th table******************************

1 X 24 = 24
2 X 24 = 48
3 X 24 = 72
4 X 24 = 96
5 X 24 = 120
6 X 24 = 144
7 X 24 = 168
8 X 24 = 192
9 X 24 = 216
10 X 24 = 240

********************** 25 th table******************************

1 X 25 = 25
2 X 25 = 50
3 X 25 = 75
4 X 25 = 100
5 X 25 = 125
6 X 25 = 150
7 X 25 = 175
8 X 25 = 200
9 X 25 = 225
10 X 25 = 250

********************** 26 th table******************************

1 X 26 = 26
2 X 26 = 52
3 X 26 = 78
4 X 26 = 104
5 X 26 = 130
6 X 26 = 156
7 X 26 = 182
8 X 26 = 208
9 X 26 = 234
10 X 26 = 260

********************** 27 th table******************************

1 X 27 = 27
2 X 27 = 54
3 X 27 = 81
4 X 27 = 108
5 X 27 = 135
6 X 27 = 162
7 X 27 = 189
8 X 27 = 216
9 X 27 = 243
10 X 27 = 270

********************** 28 th table******************************

1 X 28 = 28
2 X 28 = 56
3 X 28 = 84
4 X 28 = 112
5 X 28 = 140
6 X 28 = 168
7 X 28 = 196
8 X 28 = 224
9 X 28 = 252
10 X 28 = 280

********************** 29 th table******************************

1 X 29 = 29
2 X 29 = 58
3 X 29 = 87
4 X 29 = 116
5 X 29 = 145
6 X 29 = 174
7 X 29 = 203
8 X 29 = 232
9 X 29 = 261
10 X 29 = 290

********************** 30 th table******************************

1 X 30 = 30
2 X 30 = 60
3 X 30 = 90
4 X 30 = 120
5 X 30 = 150
6 X 30 = 180
7 X 30 = 210
8 X 30 = 240
9 X 30 = 270
10 X 30 = 300

********************** 31 th table******************************

1 X 31 = 31
2 X 31 = 62
3 X 31 = 93
4 X 31 = 124
5 X 31 = 155
6 X 31 = 186
7 X 31 = 217
8 X 31 = 248
9 X 31 = 279
10 X 31 = 310

********************** 32 th table******************************

1 X 32 = 32
2 X 32 = 64
3 X 32 = 96
4 X 32 = 128
5 X 32 = 160
6 X 32 = 192
7 X 32 = 224
8 X 32 = 256
9 X 32 = 288
10 X 32 = 320

********************** 33 th table******************************

1 X 33 = 33
2 X 33 = 66
3 X 33 = 99
4 X 33 = 132
5 X 33 = 165
6 X 33 = 198
7 X 33 = 231
8 X 33 = 264
9 X 33 = 297
10 X 33 = 330

********************** 34 th table******************************

1 X 34 = 34
2 X 34 = 68
3 X 34 = 102
4 X 34 = 136
5 X 34 = 170
6 X 34 = 204
7 X 34 = 238
8 X 34 = 272
9 X 34 = 306
10 X 34 = 340

********************** 35 th table******************************

1 X 35 = 35
2 X 35 = 70
3 X 35 = 105
4 X 35 = 140
5 X 35 = 175
6 X 35 = 210
7 X 35 = 245
8 X 35 = 280
9 X 35 = 315
10 X 35 = 350

********************** 36 th table******************************

1 X 36 = 36
2 X 36 = 72
3 X 36 = 108
4 X 36 = 144
5 X 36 = 180
6 X 36 = 216
7 X 36 = 252
8 X 36 = 288
9 X 36 = 324
10 X 36 = 360

********************** 37 th table******************************

1 X 37 = 37
2 X 37 = 74
3 X 37 = 111
4 X 37 = 148
5 X 37 = 185
6 X 37 = 222
7 X 37 = 259
8 X 37 = 296
9 X 37 = 333
10 X 37 = 370

********************** 38 th table******************************

1 X 38 = 38
2 X 38 = 76
3 X 38 = 114
4 X 38 = 152
5 X 38 = 190
6 X 38 = 228
7 X 38 = 266
8 X 38 = 304
9 X 38 = 342
10 X 38 = 380

********************** 39 th table******************************

1 X 39 = 39
2 X 39 = 78
3 X 39 = 117
4 X 39 = 156
5 X 39 = 195
6 X 39 = 234
7 X 39 = 273
8 X 39 = 312
9 X 39 = 351
10 X 39 = 390

********************** 40 th table******************************

1 X 40 = 40
2 X 40 = 80
3 X 40 = 120
4 X 40 = 160
5 X 40 = 200
6 X 40 = 240
7 X 40 = 280
8 X 40 = 320
9 X 40 = 360
10 X 40 = 400

********************** 41 th table******************************

1 X 41 = 41
2 X 41 = 82
3 X 41 = 123
4 X 41 = 164
5 X 41 = 205
6 X 41 = 246
7 X 41 = 287
8 X 41 = 328
9 X 41 = 369
10 X 41 = 410

********************** 42 th table******************************

1 X 42 = 42
2 X 42 = 84
3 X 42 = 126
4 X 42 = 168
5 X 42 = 210
6 X 42 = 252
7 X 42 = 294
8 X 42 = 336
9 X 42 = 378
10 X 42 = 420

********************** 43 th table******************************

1 X 43 = 43
2 X 43 = 86
3 X 43 = 129
4 X 43 = 172
5 X 43 = 215
6 X 43 = 258
7 X 43 = 301
8 X 43 = 344
9 X 43 = 387
10 X 43 = 430

********************** 44 th table******************************

1 X 44 = 44
2 X 44 = 88
3 X 44 = 132
4 X 44 = 176
5 X 44 = 220
6 X 44 = 264
7 X 44 = 308
8 X 44 = 352
9 X 44 = 396
10 X 44 = 440

********************** 45 th table******************************

1 X 45 = 45
2 X 45 = 90
3 X 45 = 135
4 X 45 = 180
5 X 45 = 225
6 X 45 = 270
7 X 45 = 315
8 X 45 = 360
9 X 45 = 405
10 X 45 = 450

********************** 46 th table******************************

1 X 46 = 46
2 X 46 = 92
3 X 46 = 138
4 X 46 = 184
5 X 46 = 230
6 X 46 = 276
7 X 46 = 322
8 X 46 = 368
9 X 46 = 414
10 X 46 = 460

********************** 47 th table******************************

1 X 47 = 47
2 X 47 = 94
3 X 47 = 141
4 X 47 = 188
5 X 47 = 235
6 X 47 = 282
7 X 47 = 329
8 X 47 = 376
9 X 47 = 423
10 X 47 = 470

********************** 48 th table******************************

1 X 48 = 48
2 X 48 = 96
3 X 48 = 144
4 X 48 = 192
5 X 48 = 240
6 X 48 = 288
7 X 48 = 336
8 X 48 = 384
9 X 48 = 432
10 X 48 = 480

********************** 49 th table******************************

1 X 49 = 49
2 X 49 = 98
3 X 49 = 147
4 X 49 = 196
5 X 49 = 245
6 X 49 = 294
7 X 49 = 343
8 X 49 = 392
9 X 49 = 441
10 X 49 = 490

********************** 50 th table******************************

1 X 50 = 50
2 X 50 = 100
3 X 50 = 150
4 X 50 = 200
5 X 50 = 250
6 X 50 = 300
7 X 50 = 350
8 X 50 = 400
9 X 50 = 450
10 X 50 = 500

********************** 51 th table******************************

1 X 51 = 51
2 X 51 = 102
3 X 51 = 153
4 X 51 = 204
5 X 51 = 255
6 X 51 = 306
7 X 51 = 357
8 X 51 = 408
9 X 51 = 459
10 X 51 = 510

********************** 52 th table******************************

1 X 52 = 52
2 X 52 = 104
3 X 52 = 156
4 X 52 = 208
5 X 52 = 260
6 X 52 = 312
7 X 52 = 364
8 X 52 = 416
9 X 52 = 468
10 X 52 = 520

********************** 53 th table******************************

1 X 53 = 53
2 X 53 = 106
3 X 53 = 159
4 X 53 = 212
5 X 53 = 265
6 X 53 = 318
7 X 53 = 371
8 X 53 = 424
9 X 53 = 477
10 X 53 = 530

********************** 54 th table******************************

1 X 54 = 54
2 X 54 = 108
3 X 54 = 162
4 X 54 = 216
5 X 54 = 270
6 X 54 = 324
7 X 54 = 378
8 X 54 = 432
9 X 54 = 486
10 X 54 = 540

********************** 55 th table******************************

1 X 55 = 55
2 X 55 = 110
3 X 55 = 165
4 X 55 = 220
5 X 55 = 275
6 X 55 = 330
7 X 55 = 385
8 X 55 = 440
9 X 55 = 495
10 X 55 = 550

********************** 56 th table******************************

1 X 56 = 56
2 X 56 = 112
3 X 56 = 168
4 X 56 = 224
5 X 56 = 280
6 X 56 = 336
7 X 56 = 392
8 X 56 = 448
9 X 56 = 504
10 X 56 = 560

********************** 57 th table******************************

1 X 57 = 57
2 X 57 = 114
3 X 57 = 171
4 X 57 = 228
5 X 57 = 285
6 X 57 = 342
7 X 57 = 399
8 X 57 = 456
9 X 57 = 513
10 X 57 = 570

********************** 58 th table******************************

1 X 58 = 58
2 X 58 = 116
3 X 58 = 174
4 X 58 = 232
5 X 58 = 290
6 X 58 = 348
7 X 58 = 406
8 X 58 = 464
9 X 58 = 522
10 X 58 = 580

********************** 59 th table******************************

1 X 59 = 59
2 X 59 = 118
3 X 59 = 177
4 X 59 = 236
5 X 59 = 295
6 X 59 = 354
7 X 59 = 413
8 X 59 = 472
9 X 59 = 531
10 X 59 = 590

********************** 60 th table******************************

1 X 60 = 60
2 X 60 = 120
3 X 60 = 180
4 X 60 = 240
5 X 60 = 300
6 X 60 = 360
7 X 60 = 420
8 X 60 = 480
9 X 60 = 540
10 X 60 = 600

********************** 61 th table******************************

1 X 61 = 61
2 X 61 = 122
3 X 61 = 183
4 X 61 = 244
5 X 61 = 305
6 X 61 = 366
7 X 61 = 427
8 X 61 = 488
9 X 61 = 549
10 X 61 = 610

********************** 62 th table******************************

1 X 62 = 62
2 X 62 = 124
3 X 62 = 186
4 X 62 = 248
5 X 62 = 310
6 X 62 = 372
7 X 62 = 434
8 X 62 = 496
9 X 62 = 558
10 X 62 = 620

********************** 63 th table******************************

1 X 63 = 63
2 X 63 = 126
3 X 63 = 189
4 X 63 = 252
5 X 63 = 315
6 X 63 = 378
7 X 63 = 441
8 X 63 = 504
9 X 63 = 567
10 X 63 = 630

********************** 64 th table******************************

1 X 64 = 64
2 X 64 = 128
3 X 64 = 192
4 X 64 = 256
5 X 64 = 320
6 X 64 = 384
7 X 64 = 448
8 X 64 = 512
9 X 64 = 576
10 X 64 = 640

********************** 65 th table******************************

1 X 65 = 65
2 X 65 = 130
3 X 65 = 195
4 X 65 = 260
5 X 65 = 325
6 X 65 = 390
7 X 65 = 455
8 X 65 = 520
9 X 65 = 585
10 X 65 = 650

********************** 66 th table******************************

1 X 66 = 66
2 X 66 = 132
3 X 66 = 198

4 X 66 = 264
5 X 66 = 330
6 X 66 = 396
7 X 66 = 462
8 X 66 = 528
9 X 66 = 594
10 X 66 = 660

********************** 67 th table******************************

1 X 67 = 67
2 X 67 = 134
3 X 67 = 201
4 X 67 = 268
5 X 67 = 335
6 X 67 = 402
7 X 67 = 469
8 X 67 = 536
9 X 67 = 603
10 X 67 = 670

********************** 68 th table******************************

1 X 68 = 68
2 X 68 = 136
3 X 68 = 204
4 X 68 = 272
5 X 68 = 340
6 X 68 = 408
7 X 68 = 476
8 X 68 = 544
9 X 68 = 612
10 X 68 = 680

********************** 69 th table******************************

1 X 69 = 69
2 X 69 = 138
3 X 69 = 207
4 X 69 = 276
5 X 69 = 345
6 X 69 = 414
7 X 69 = 483
8 X 69 = 552
9 X 69 = 621
10 X 69 = 690

********************** 70 th table******************************

1 X 70 = 70
2 X 70 = 140
3 X 70 = 210
4 X 70 = 280
5 X 70 = 350
6 X 70 = 420
7 X 70 = 490
8 X 70 = 560
9 X 70 = 630
10 X 70 = 700

********************** 71 th table******************************

1 X 71 = 71
2 X 71 = 142
3 X 71 = 213
4 X 71 = 284
5 X 71 = 355
6 X 71 = 426
7 X 71 = 497
8 X 71 = 568
9 X 71 = 639
10 X 71 = 710

********************** 72 th table******************************

1 X 72 = 72
2 X 72 = 144
3 X 72 = 216
4 X 72 = 288
5 X 72 = 360
6 X 72 = 432
7 X 72 = 504
8 X 72 = 576
9 X 72 = 648
10 X 72 = 720

********************** 73 th table******************************

1 X 73 = 73
2 X 73 = 146
3 X 73 = 219
4 X 73 = 292
5 X 73 = 365
6 X 73 = 438
7 X 73 = 511
8 X 73 = 584
9 X 73 = 657
10 X 73 = 730

********************** 74 th table******************************

1 X 74 = 74
2 X 74 = 148
3 X 74 = 222
4 X 74 = 296
5 X 74 = 370
6 X 74 = 444
7 X 74 = 518
8 X 74 = 592
9 X 74 = 666
10 X 74 = 740

********************** 75 th table******************************

1 X 75 = 75
2 X 75 = 150
3 X 75 = 225
4 X 75 = 300
5 X 75 = 375
6 X 75 = 450
7 X 75 = 525
8 X 75 = 600
9 X 75 = 675
10 X 75 = 750

********************** 76 th table******************************

1 X 76 = 76
2 X 76 = 152
3 X 76 = 228
4 X 76 = 304
5 X 76 = 380
6 X 76 = 456
7 X 76 = 532
8 X 76 = 608
9 X 76 = 684
10 X 76 = 760

********************** 77 th table******************************

1 X 77 = 77
2 X 77 = 154
3 X 77 = 231
4 X 77 = 308
5 X 77 = 385
6 X 77 = 462
7 X 77 = 539
8 X 77 = 616
9 X 77 = 693
10 X 77 = 770

********************** 78 th table******************************

1 X 78 = 78
2 X 78 = 156
3 X 78 = 234
4 X 78 = 312
5 X 78 = 390
6 X 78 = 468
7 X 78 = 546
8 X 78 = 624
9 X 78 = 702
10 X 78 = 780

********************** 79 th table******************************

1 X 79 = 79
2 X 79 = 158
3 X 79 = 237
4 X 79 = 316
5 X 79 = 395
6 X 79 = 474
7 X 79 = 553
8 X 79 = 632
9 X 79 = 711
10 X 79 = 790

********************** 80 th table******************************

1 X 80 = 80
2 X 80 = 160
3 X 80 = 240
4 X 80 = 320
5 X 80 = 400
6 X 80 = 480
7 X 80 = 560
8 X 80 = 640
9 X 80 = 720
10 X 80 = 800

********************** 81 th table******************************

1 X 81 = 81
2 X 81 = 162
3 X 81 = 243
4 X 81 = 324
5 X 81 = 405
6 X 81 = 486
7 X 81 = 567
8 X 81 = 648
9 X 81 = 729
10 X 81 = 810

********************** 82 th table******************************

1 X 82 = 82
2 X 82 = 164
3 X 82 = 246
4 X 82 = 328
5 X 82 = 410
6 X 82 = 492
7 X 82 = 574
8 X 82 = 656
9 X 82 = 738
10 X 82 = 820

********************** 83 th table******************************

1 X 83 = 83
2 X 83 = 166
3 X 83 = 249
4 X 83 = 332
5 X 83 = 415
6 X 83 = 498
7 X 83 = 581
8 X 83 = 664
9 X 83 = 747
10 X 83 = 830

********************** 84 th table******************************

1 X 84 = 84
2 X 84 = 168
3 X 84 = 252
4 X 84 = 336
5 X 84 = 420
6 X 84 = 504
7 X 84 = 588
8 X 84 = 672
9 X 84 = 756
10 X 84 = 840

********************** 85 th table******************************

1 X 85 = 85
2 X 85 = 170
3 X 85 = 255
4 X 85 = 340
5 X 85 = 425
6 X 85 = 510
7 X 85 = 595
8 X 85 = 680
9 X 85 = 765
10 X 85 = 850

********************** 86 th table******************************

1 X 86 = 86
2 X 86 = 172
3 X 86 = 258
4 X 86 = 344
5 X 86 = 430
6 X 86 = 516
7 X 86 = 602
8 X 86 = 688
9 X 86 = 774
10 X 86 = 860

********************** 87 th table******************************

1 X 87 = 87
2 X 87 = 174
3 X 87 = 261
4 X 87 = 348
5 X 87 = 435
6 X 87 = 522
7 X 87 = 609
8 X 87 = 696
9 X 87 = 783
10 X 87 = 870

********************** 88 th table******************************

1 X 88 = 88
2 X 88 = 176
3 X 88 = 264
4 X 88 = 352
5 X 88 = 440
6 X 88 = 528
7 X 88 = 616
8 X 88 = 704
9 X 88 = 792
10 X 88 = 880

********************** 89 th table******************************

1 X 89 = 89
2 X 89 = 178
3 X 89 = 267
4 X 89 = 356
5 X 89 = 445
6 X 89 = 534
7 X 89 = 623
8 X 89 = 712
9 X 89 = 801
10 X 89 = 890

********************** 90 th table******************************

1 X 90 = 90
2 X 90 = 180
3 X 90 = 270
4 X 90 = 360
5 X 90 = 450
6 X 90 = 540
7 X 90 = 630
8 X 90 = 720
9 X 90 = 810
10 X 90 = 900

********************** 91 th table******************************

1 X 91 = 91
2 X 91 = 182
3 X 91 = 273
4 X 91 = 364
5 X 91 = 455
6 X 91 = 546
7 X 91 = 637
8 X 91 = 728
9 X 91 = 819
10 X 91 = 910

********************** 92 th table******************************

1 X 92 = 92
2 X 92 = 184
3 X 92 = 276
4 X 92 = 368
5 X 92 = 460
6 X 92 = 552
7 X 92 = 644
8 X 92 = 736
9 X 92 = 828
10 X 92 = 920

********************** 93 th table******************************

1 X 93 = 93
2 X 93 = 186
3 X 93 = 279
4 X 93 = 372
5 X 93 = 465
6 X 93 = 558
7 X 93 = 651
8 X 93 = 744
9 X 93 = 837
10 X 93 = 930

********************** 94 th table******************************

1 X 94 = 94
2 X 94 = 188
3 X 94 = 282
4 X 94 = 376
5 X 94 = 470
6 X 94 = 564
7 X 94 = 658
8 X 94 = 752
9 X 94 = 846
10 X 94 = 940

********************** 95 th table******************************

1 X 95 = 95
2 X 95 = 190
3 X 95 = 285
4 X 95 = 380
5 X 95 = 475
6 X 95 = 570
7 X 95 = 665
8 X 95 = 760
9 X 95 = 855
10 X 95 = 950

********************** 96 th table******************************

1 X 96 = 96
2 X 96 = 192
3 X 96 = 288
4 X 96 = 384
5 X 96 = 480
6 X 96 = 576
7 X 96 = 672
8 X 96 = 768
9 X 96 = 864
10 X 96 = 960

********************** 97 th table******************************

1 X 97 = 97
2 X 97 = 194
3 X 97 = 291
4 X 97 = 388
5 X 97 = 485
6 X 97 = 582
7 X 97 = 679
8 X 97 = 776
9 X 97 = 873
10 X 97 = 970

********************** 98 th table******************************

1 X 98 = 98
2 X 98 = 196
3 X 98 = 294
4 X 98 = 392
5 X 98 = 490
6 X 98 = 588
7 X 98 = 686
8 X 98 = 784
9 X 98 = 882
10 X 98 = 980

********************** 99 th table******************************

1 X 99 = 99
2 X 99 = 198
3 X 99 = 297
4 X 99 = 396
5 X 99 = 495
6 X 99 = 594
7 X 99 = 693
8 X 99 = 792
9 X 99 = 891
10 X 99 = 990

********************** 100 th table******************************

1 X 100 = 100
2 X 100 = 200
3 X 100 = 300
4 X 100 = 400
5 X 100 = 500
6 X 100 = 600
7 X 100 = 700
8 X 100 = 800
9 X 100 = 900
10 X 100 = 1000